name: Release binaries

on:
  release:
    types: created

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Test
      run: go test -v ./...

    - name: Build Linux
      run: go build -v ./... -ldflags="-s -w"
      env:
        GOOS: windows
        GOARCH: amd64

    - name: Build Windows
      run: go build -v ./... -ldflags="-s -w"
      env:
        GOOS: linux
        GOARCH: amd64

    - name: Run UPX Linux
      uses: crazy-max/ghaction-upx@v1
      with:
        version: latest
        file: ./fp93

    - name: Run UPX Windows
      uses: crazy-max/ghaction-upx@v1
      with:
        version: latest
        file: ./fp93.exe

    - name: Upload artifacts
      uses: Roang-zero1/github-upload-release-artifacts-action@master
      with:
        args:
        - fp93
        - fp93.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
