name: Release binaries

on:
  release:
    types: created

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Test
      run: go test -v ./...

    - name: Build Windows
      run: go build -v ./... -ldflags="-s -w"
      env:
        GOOS: windows
        GOARCH: amd64

    - name: Build Linux
      run: go build -v ./... -ldflags="-s -w" -o fp93.linux
      env:
        GOOS: linux
        GOARCH: amd64
        
    - name: Build MacOS
      run: go build -v ./... -ldflags="-s -w" -o fp93.macos
      env:
        GOOS: darwin
        GOARCH: amd64

    - name: Run UPX Linux
      uses: crazy-max/ghaction-upx@v1
      with:
        version: latest
        file: ./fp93.linux

    - name: Run UPX Windows
      uses: crazy-max/ghaction-upx@v1
      with:
        version: latest
        file: ./fp93.exe
        
    - name: Run UPX MacOS
      uses: crazy-max/ghaction-upx@v1
      with:
        version: latest
        file: ./fp93.macos

    - name: Upload artifacts
      uses: Roang-zero1/github-upload-release-artifacts-action@master
      with:
        args:
        - fp93.linux
        - fp93.macos
        - fp93.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
